#server
server:
    address: localhost
    port: 8080

# Log
logging:
    level:
        com:
            spring: DEBUG
        org:
            hibernate:
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
                SQL: DEBUG
        root: info

spring:
    jpa:
        database: mysql
        show-sql: 'true'
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: 'true'
    devtools:
        restart:
            enabled: 'true'
        livereload:
            enabled: 'true'
    security:
        # Spring Security default user, password
        user:
            password: '1234'
            name: user
    #Mysql
    datasource:
        username: Jamong
        password: Jamong
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/Jamong?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    # Thymeleaf
    thymeleaf:
        cache: false

    profiles:
        group:
            "local" : "local, jwt, oauth"
        active : local
---
spring:
    config:
        activate:
            on-profile: "local"